- name: "after coreth x subnet-evm"
  color: "98E19D"
  description: "To be done after merging the coreth and subnet-evm codebases"
- name: "after libevm"
  color: "98E19D"
  description: "To be done only after using libevm for good"
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "ci"
  color: "15E277"
- name: "cleanup"
  color: "49C111"
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"
- name: "Do not merge"
  color: "b60205"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "e upgrade"
  color: "F5B85A"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "gossiping upgrade"
  color: "d93f0b"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "incident response"
  color: "DAD20E"
- name: "integration-testing"
  color: "0A0235"
  description: "Refactoring of unit tests to fixture-based integration"
- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"
- name: "network upgrade"
  color: "1d76db"
  description: "Requires network upgrade"
- name: "Pending another PR"
  color: "fef2c0"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "reproducible load tests"
  color: "1d76db"
- name: "testing"
  color: "687388"
  description: "Anything testing-related"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
