# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 10m

issues:
  new: true

linters:
  enable:
    - copyloopvar
    - errorlint
    - goimports
    - misspell
    - nolintlint
    - unconvert
    - wastedassign
    - whitespace

linters-settings:
  errorlint:
    errorf: false
