version: "2"
run:
  tests: true

linters:
  default: none
  enable:
    - bidichk
    - copyloopvar
    - durationcheck
    - gocheckcompilerdirectives
    - govet
    - ineffassign
    - mirror
    - misspell
    - reassign
    # - revive # only certain checks enabled
    - staticcheck 
    - unconvert
    - unused
    - whitespace
  settings:
    goconst:
      min-len: 3 # minimum length of string constant
      min-occurrences: 6 # minimum number of occurrences
    staticcheck:
      checks:
        - all
        # There's a lot of legacy code that triggers these warnings after upgrading golangci-lint.
        - -QF1001
        - -QF1002
        - -QF1003
        - -QF1006
        - -QF1008
        - -QF1010
        - -SA1019
        - -SA4009
        - -SA4010
        - -SA9003
        - -ST1003
        - -ST1008
        - -ST1016

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unused
        # Exclude unused geth symbols from ethclient/ethclient.go to simplify upgrading Geth to a newer version.
        path: ethclient\/ethclient\.go
        text: (type `rpcProgress`|func `\(\*rpcProgress\)\.toSyncProgress`) is unused
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
