# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert
    - typecheck
    - unused
    - staticcheck
    - bidichk
    - durationcheck
    - copyloopvar
    - whitespace
    # - revive # only certain checks enabled
    - durationcheck
    - gocheckcompilerdirectives
    - reassign
    - mirror
    - tenv
    - errcheck

issues:
  exclude-rules:
    - path: "_test\\.go"
      text: "SA1019: rand\\.(Seed|Read) has been deprecated since Go 1\\.20"
      linters:
        - staticcheck

    - path-except: "(plugin\\/.+\\.go|.+_ext\\.go)"
      linters:
        - errcheck
        - gosimple
        - govet
        - staticcheck
