# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - whitespace

linters-settings:
  goconst:
    min-occurrences: 6 # minimum number of occurrences
    ignore-tests: true
