# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert
    - typecheck
    - unused
    # - staticcheck
    - bidichk
    - durationcheck
    - copyloopvar
    - whitespace
    # - revive # only certain checks enabled
    - durationcheck
    - gocheckcompilerdirectives
    - reassign
    - mirror
    - tenv
