name: CI
on:
  push:
    branches: [ chain4travel, dev ]
  pull_request:
    branches: [ chain4travel, dev ]
  workflow_dispatch:
    inputs:
      caminoethvmBranch:
        description: 'caminoethvm branch'
        required: true
        default: 'chain4travel'
      caminogoBranch:
        description: 'caminogo branch'
        required: false
        default: ''

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - name: check out
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: actions/checkout@v3
    - name: check out ${{ github.event.inputs.caminoethvmBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.caminoethvmBranch }}
    - name: check out chain4travel/caminogo ${{ github.event.inputs.caminogoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.caminogoBranch != '' }}
      uses: actions/checkout@v3
      with:
        repository: chain4travel/caminogo
        ref: ${{ github.event.inputs.caminogoBranch }}
        path: caminogo
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: change caminogo dep
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.caminogoBranch != '' }}
      run: |
        go mod edit -replace github.com/ava-labs/avalanchego=./caminogo
        go mod tidy
        go clean -modcache # avoid conflicts with the golangci-lint-action cache
    - run: ./scripts/lint_allowed_geth_imports.sh
      shell: bash
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.51
        working-directory: .
        args: --timeout 3m
        skip-go-installation: true
  test:
    name: Golang Unit Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.18']
        os: [macos-11.0, ubuntu-20.04]
    steps:
    - name: check out
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: actions/checkout@v3
    - name: check out ${{ github.event.inputs.caminoethvmBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.caminoethvmBranch }}
    - name: check out chain4travel/caminogo ${{ github.event.inputs.caminogoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.caminogoBranch != '' }}
      uses: actions/checkout@v3
      with:
        repository: chain4travel/caminogo
        ref: ${{ github.event.inputs.caminogoBranch }}
        path: caminogo
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: change caminogo dep
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.caminogoBranch != '' }}
      run: |
        go mod edit -replace github.com/ava-labs/avalanchego=./caminogo
        go mod tidy
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh
      shell: bash
    - run: ./scripts/coverage.sh
      shell: bash
  test-race:
    name: Golang Unit Tests Race Detection v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.18']
        os: [ubuntu-20.04]
    steps:
    - name: check out
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: actions/checkout@v3
    - name: check out ${{ github.event.inputs.caminoethvmBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.caminoethvmBranch }}
    - uses: actions/checkout@v3
    - name: check out chain4travel/caminogo ${{ github.event.inputs.caminogoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.caminogoBranch != '' }}
      uses: actions/checkout@v3
      with:
        repository: chain4travel/caminogo
        ref: ${{ github.event.inputs.caminogoBranch }}
        path: caminogo
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: change caminogo dep
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.caminogoBranch != '' }}
      run: |
        go mod edit -replace github.com/ava-labs/avalanchego=./caminogo
        go mod tidy
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh -race
      shell: bash
