name: CI
on:
  push:
    branches-ignore: ["*"]

jobs:
  e2e:
    name: Golang E2E Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.18' ]
        os: [ ubuntu-20.04 ]
    steps:
    - uses: actions/checkout@v2
    - name: check out ${{ github.event.inputs.caminogoRepo }} ${{ github.event.inputs.caminogoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.caminogoRepo }}
        ref: ${{ github.event.inputs.caminogoBranch }}
        path: caminogo
        token: ${{ secrets.CAMINO_PAT }}
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: change caminogo dep
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        go mod edit -replace github.com/chain4travel/caminogo=./caminogo
        go mod tidy
    - name: prepare caminogo directory for docker copy
      if: ${{ github.event_name == 'workflow_dispatch' }}
      # mv caminogo/ to nested dir caminogo/caminogo/
      # required because docker instruction "COPY dir ." copies dir/* to .
      run: mkdir caminogo_tmp && mv caminogo caminogo_tmp && mv caminogo_tmp caminogo
    - run: .github/workflows/run_e2e_tests.sh --parallelism 1 --client-id $KURTOSIS_CLIENT_ID --client-secret $KURTOSIS_CLIENT_SECRET
      shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        KURTOSIS_CLIENT_ID: ${{ secrets.KURTOSIS_CLIENT_ID }}
        KURTOSIS_CLIENT_SECRET: ${{ secrets.KURTOSIS_CLIENT_SECRET }}
