name: CI
on:
  push:
    branches-ignore: ["**"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: update dependencies
        run: git submodule update --init
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: ./scripts/lint_allowed_geth_imports.sh
        shell: bash
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.47
          working-directory: .
          args: --timeout 3m
  test:
    name: Golang Unit Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.18']
        os: [macos-11.0, ubuntu-18.04, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: update dependencies
      run: git submodule update --init
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh
      shell: bash
    - run: ./scripts/coverage.sh
      shell: bash
  test-race:
    name: Golang Unit Tests Race Detection v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.18']
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v3
    - name: update dependencies
      run: git submodule update --init
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh -race
      shell: bash
  e2e:
    name: Golang E2E Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.18' ]
        os: [ ubuntu-20.04 ]
    steps:
    - uses: actions/checkout@v3
    - name: update dependencies
      run: git submodule update --init
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: prepare avalanchego directory for docker copy
      if: ${{ github.event_name == 'workflow_dispatch' }}
      # mv avalanchego/ to nested dir avalanchego/avalanchego/
      # required because docker instruction "COPY dir ." copies dir/* to .
      run: mkdir avalanchego_tmp && mv avalanchego avalanchego_tmp && mv avalanchego_tmp avalanchego
    - run: .github/workflows/run_e2e_tests.sh --parallelism 1 --client-id $KURTOSIS_CLIENT_ID --client-secret $KURTOSIS_CLIENT_SECRET
      shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        KURTOSIS_CLIENT_ID: ${{ secrets.KURTOSIS_CLIENT_ID }}
        KURTOSIS_CLIENT_SECRET: ${{ secrets.KURTOSIS_CLIENT_SECRET }}
